apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
  name: pages
spec:
  replicas: {{ .Values.deployment.replicas }} 
  selector:
    matchLabels:
      app: pages
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
    spec:
      containers:
      - image: dellcloud/pages:1.0
        name: pages
